Repository pytoyoda/pytoyoda, pull requests merged in 2025-03, with the labels that each got.

#8 Add missing permissions to workflows
  .github/workflows/build.yml
  .github/workflows/linting.yml
  .github/workflows/testing.yml
Labels: :wrench: enhancement

#17 Fix pre-commit code quality
  renovate.json
Labels: :game_die: dependencies

#20 add bot label
  renovate.json
Labels: :wrench: enhancement

#11 Add HVAC support
  pytoyoda/api.py
  pytoyoda/const.py
  pytoyoda/models/climate.py
  pytoyoda/models/endpoints/climate.py
  pytoyoda/models/endpoints/command.py
  pytoyoda/models/vehicle.py
  simple_client_example.py
Labels: :rocket: feature

#29 Test and build also on python 3.13
  .github/workflows/build.yml
  .github/workflows/python-publish.yml
  .github/workflows/testing.yml
  README.md
  pyproject.toml
Labels: :game_die: dependencies

#30 Enforce docstring formatting
  pyproject.toml
Labels: :memo: documentation

#31 Use more consistent docstrings
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  pytoyoda/api.py
  pytoyoda/client.py
  pytoyoda/controller.py
  pytoyoda/models/electric_status.py
  pytoyoda/models/nofication.py
  pytoyoda/models/service_history.py
  pytoyoda/models/vehicle.py
  pytoyoda/utils/helpers.py
  pytoyoda/utils/log_utils.py
  pytoyoda/utils/models.py
  tests/integration_tests/test_authentication.py
  tests/unit_tests/test_api.py
  tests/unit_tests/test_init.py
Labels: :memo: documentation

#35 Test `pdoc` auto dosumentation
  .github/workflows/docs.yml
  poetry.lock
  pyproject.toml
  pytoyoda/controller.py
Labels: :memo: documentation

#36 adjust pdocs module name
  .github/workflows/docs.yml
Labels: :memo: documentation

#38 adjust output folder
  .github/workflows/docs.yml
Labels: :memo: documentation

#32 Fix deprecation warning in `simple_client_example.py`
  simple_client_example.py
Labels: :wrench: enhancement

#33 Use in memory cache file instead of writing cache file to disk
  pytoyoda/controller.py
  simple_client_example.py
  tests/integration_tests/conftest.py
  tests/integration_tests/data/cached_token.json
  tests/integration_tests/test_authentication.py
Labels: :wrench: enhancement

#34 Replace coverage with pytest-cov and upload test results
  .github/workflows/testing.yml
  README.md
  poetry.lock
  pyproject.toml
  pytoyoda/__init__.py
  renovate.json
Labels: :wrench: enhancement

#39 Refactor controller module
  pytoyoda/controller.py
  tests/integration_tests/conftest.py
  tests/integration_tests/test_authentication.py
Labels: :wrench: enhancement

#40 Update dependencies an switch to loguru
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  pytoyoda/api.py
  pytoyoda/client.py
  pytoyoda/controller.py
  pytoyoda/utils/conversions.py
  simple_client_example.py
Labels: :game_die: dependencies, :wrench: enhancement

#43 Add autofix to linitng workflow
  .github/workflows/autofix.yml
Labels: :wrench: enhancement

#44 Using pre-commit ci instead of autofix
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  tests/unit_tests/test_api.py
  tests/unit_tests/test_utils/test_logs.py
Labels: :wrench: enhancement

#41 Refactor API Module
  pytoyoda/api.py
  pytoyoda/client.py
  pytoyoda/models/vehicle.py
  simple_client_example.py
Labels: :warning: breaking change, :wrench: enhancement

#45 Refactor client module
  .pre-commit-config.yaml
  pytoyoda/client.py
  simple_client_example.py
  tests/integration_tests/test_authentication.py
Labels: :warning: breaking change, :wrench: enhancement

#47 Refactor utils
  pytoyoda/models/endpoints/climate.py
  pytoyoda/models/endpoints/command.py
  pytoyoda/utils/conversions.py
  pytoyoda/utils/formatters.py
  pytoyoda/utils/helpers.py
  pytoyoda/utils/locale.py
  pytoyoda/utils/log_utils.py
  pytoyoda/utils/models.py
  tests/unit_tests/test_utils/test_logs.py
Labels: :wrench: enhancement

#48 Switch completely to pydantic v2 models
  .github/workflows/pre-commit.yml
  pytoyoda/api.py
  pytoyoda/models/endpoints/account.py
  pytoyoda/models/endpoints/climate.py
  pytoyoda/models/endpoints/command.py
  pytoyoda/models/endpoints/common.py
  pytoyoda/models/endpoints/electric.py
  pytoyoda/models/endpoints/location.py
  pytoyoda/models/endpoints/notifications.py
  pytoyoda/models/endpoints/service_history.py
  pytoyoda/models/endpoints/status.py
  pytoyoda/models/endpoints/telemetry.py
  pytoyoda/models/endpoints/trips.py
  pytoyoda/models/endpoints/vehicle_guid.py
  pytoyoda/models/endpoints/vehicle_health.py
  pytoyoda/models/vehicle.py
  pytoyoda/utils/models.py
Labels: :game_die: dependencies, :wrench: enhancement

#49 Use pydantic and unify represantation handling for api models
  pytoyoda/const.py
  pytoyoda/models/climate.py
  pytoyoda/models/dashboard.py
  pytoyoda/models/electric_status.py
  pytoyoda/models/endpoints/account.py
  pytoyoda/models/endpoints/climate.py
  pytoyoda/models/endpoints/command.py
  pytoyoda/models/endpoints/common.py
  pytoyoda/models/endpoints/electric.py
  pytoyoda/models/endpoints/location.py
  pytoyoda/models/endpoints/notifications.py
  pytoyoda/models/endpoints/service_history.py
  pytoyoda/models/endpoints/status.py
  pytoyoda/models/endpoints/telemetry.py
  pytoyoda/models/endpoints/trips.py
  pytoyoda/models/endpoints/vehicle_guid.py
  pytoyoda/models/endpoints/vehicle_health.py
  pytoyoda/models/location.py
  pytoyoda/models/lock_status.py
  pytoyoda/models/nofication.py
  pytoyoda/models/service_history.py
  pytoyoda/models/summary.py
  pytoyoda/models/trips.py
  pytoyoda/models/vehicle.py
  pytoyoda/utils/models.py
  simple_client_example.py
Labels: :warning: breaking change, :wrench: enhancement

#51 Adjust endpoint models
  pytoyoda/models/endpoints/account.py
  pytoyoda/models/endpoints/climate.py
  pytoyoda/models/endpoints/command.py
  pytoyoda/models/endpoints/common.py
  pytoyoda/models/endpoints/electric.py
  pytoyoda/models/endpoints/location.py
  pytoyoda/models/endpoints/notifications.py
Labels: :wrench: enhancement

#53 Bring back endpoint tester
  .gitignore
  README.md
  poetry.lock
  pyproject.toml
  sandbox/endpoint_tester.py
  sandbox/endpoints_to_test.py
  sandbox/simple_client_example.py
Labels: :wrench: enhancement

#55 Improve vehicle model error handling
  pytoyoda/models/vehicle.py
Labels: :bug: bug, :wrench: enhancement

#60 Fix and adjust car type determination
  pytoyoda/models/vehicle.py
Labels: :bug: bug
