Repository pytoyoda/pytoyoda, pull requests merged in 2025-04, with the labels that each got.

#87 Adopting headers to latest client information
  poetry.lock
  pytoyoda/const.py
  pytoyoda/controller.py
  pytoyoda/utils/helpers.py
Labels: :bug: bug

#88 Enable sonarqube scanning and replace codecov
  .github/workflows/testing.yml
  .gitignore
  codecov.yml
  sonar-project.properties
Labels: :wrench: enhancement

#89 fix sonarqube test folder
  sonar-project.properties
Labels: :bug: bug

#90 use sonar sources instead of tests
  .github/workflows/testing.yml
  sonar-project.properties
Labels: :wrench: enhancement

#91 Extend ruff rules and fix MPG conversion
  .pre-commit-config.yaml
  pyproject.toml
  pytoyoda/__init__.py
  pytoyoda/api.py
  pytoyoda/client.py
  pytoyoda/const.py
  pytoyoda/controller.py
  pytoyoda/models/__init__.py
  pytoyoda/models/climate.py
  pytoyoda/models/dashboard.py
  pytoyoda/models/electric_status.py
  pytoyoda/models/endpoints/__init__.py
  pytoyoda/models/endpoints/account.py
  pytoyoda/models/endpoints/climate.py
  pytoyoda/models/endpoints/command.py
  pytoyoda/models/endpoints/common.py
  pytoyoda/models/endpoints/electric.py
  pytoyoda/models/endpoints/location.py
  pytoyoda/models/endpoints/notifications.py
  pytoyoda/models/endpoints/service_history.py
  pytoyoda/models/endpoints/status.py
  pytoyoda/models/endpoints/telemetry.py
  pytoyoda/models/endpoints/trips.py
  pytoyoda/models/endpoints/vehicle_guid.py
  pytoyoda/models/endpoints/vehicle_health.py
  pytoyoda/models/location.py
  pytoyoda/models/lock_status.py
  pytoyoda/models/nofication.py
  pytoyoda/models/service_history.py
  pytoyoda/models/summary.py
  pytoyoda/models/trips.py
  pytoyoda/models/vehicle.py
  pytoyoda/utils/conversions.py
  pytoyoda/utils/formatters.py
  pytoyoda/utils/helpers.py
  pytoyoda/utils/locale.py
  pytoyoda/utils/log_utils.py
  pytoyoda/utils/models.py
  tests/integration_tests/test_authentication.py
  tests/unit_tests/test_utils/test_conversions.py
Labels: :wrench: enhancement

#95 Fix lazy logging
  pytoyoda/client.py
  pytoyoda/utils/conversions.py
Labels: :wrench: enhancement

#77 Api for update_vehicle_electric_realtime_status
  pytoyoda/api.py
  pytoyoda/const.py
Labels: :rocket: feature

#96 Add codacy coverage reporting
  .github/workflows/testing.yml
Labels: :wrench: enhancement

#97 Create .codacy.yaml
  .codacy.yaml
Labels: :wrench: enhancement

#98 Enable codacy ruleset
  .codacy.yaml
Labels: :wrench: enhancement

#99 Fix car type calculation
  pytoyoda/models/vehicle.py
Labels: :bug: bug

#100 adjust naming for electric realtime status refresh
  pytoyoda/api.py
  pytoyoda/models/vehicle.py
Labels: :wrench: enhancement

#102 Fix asstertion error in summaries calculation
  pytoyoda/models/vehicle.py
Labels: :bug: bug
